config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/profile.rb
class Profile < ApplicationRecord
  extend FriendlyId
  friendly_id :username, use: :slugged
  has_one_attached :avatar
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:name, :username, :description, :job_title, :location, :avatar)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Sign Up", signup_path %> or 
  <%= link_to "Log In", login_path %>
<% end %>
<p id="notice"><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zanta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <div class="container p-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.file_field :avatar %>


  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :job_title, style: "display: block" %>
    <%= form.text_field :job_title %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>">
  <p>
    <strong>Name:</strong>
    <%= profile.name %>
  </p>

  <p>
    <strong>Username:</strong>
    <%= profile.username %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= profile.description %>
  </p>

  <p>
    <strong>Job title:</strong>
    <%= profile.job_title %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= profile.location %>
  </p>

</div>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Show this profile", @profile %> |
  <%= link_to "Back to profiles", profiles_path %>
</div>

app/views/profiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Profiles</h1>

<div id="profiles">
  <% @profiles.each do |profile| %>
    <%= render profile %>
    <p>
      <%= link_to "Show this profile", profile %>
    </p>
  <% end %>
</div>

<%= link_to "New profile", new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Back to profiles", profiles_path %>
</div>

app/views/profiles/show.html.erb
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-md-9 col-lg-7 col-xl-5">
        <div class="card" style="border-radius: 15px; background-color: #93e2bb;">
          <div class="card-body p-4 text-black">
            <div>
              
              <div class="d-flex align-items-center justify-content-between mb-3">
                <p class="small mb-0"><i class="far fa-clock me-2"></i>3 hrs</p>
                <p class="fw-bold mb-0">$90</p>
              </div>
            </div>
            <div class="d-flex align-items-center mb-4">
              <div class="flex-shrink-0">
                    <%= image_tag(@profile.avatar, class: "img-fluid rounded-circle border border-dark border-3", width: 70, height: 50) %>
             
              </div>
              <div class="flex-grow-1 ms-3">
                <div class="d-flex flex-row align-items-center mb-2">
                  <p class="mb-0 me-2">@sheisme</p>
                  <ul class="mb-0 list-unstyled d-flex flex-row" style="color: #1B7B2C;">
                    <li>
                      <i class="fas fa-star fa-xs"></i>
                    </li>
                    <li>
                      <i class="fas fa-star fa-xs"></i>
                    </li>
                    <li>
                      <i class="fas fa-star fa-xs"></i>
                    </li>
                    <li>
                      <i class="fas fa-star fa-xs"></i>
                    </li>
                    <li>
                      <i class="fas fa-star fa-xs"></i>
                    </li>
                  </ul>
                </div>
                <div>
                  <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-dark btn-rounded btn-sm"
                    data-mdb-ripple-color="dark">+ Follow</button>
                  <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-dark btn-rounded btn-sm"
                    data-mdb-ripple-color="dark">See profile</button>
                  <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-dark btn-floating btn-sm"
                    data-mdb-ripple-color="dark"><i class="fas fa-comment"></i></button>
                </div>
              </div>
            </div>
            <hr>
            <p class="my-4 pb-1">52 comments</p>
            <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-success btn-rounded btn-block btn-lg"><i
                class="far fa-clock me-2"></i>Book now</button>
          </div>
        </div>
      </div>
    </div>
  </div>



<div class="row">
  <div class="col-12">
    <%= image_tag(@profile.avatar, class: "rounded-circle img-fluid img-thumbnail", width: 100, height: 100) %>
  </div>
</div>

<div class="flex-grow-1 ms-3">
                <div class="d-flex flex-row align-items-center mb-2">
                  <p class="mb-0 me-2">@sheisme</p>
                  <ul class="mb-0 list-unstyled d-flex flex-row" style="color: #1B7B2C;">
                    <li>
                      <i class="fas fa-star fa-xs"></i>
                    </li>
                    <li>
                      <i class="fas fa-star fa-xs"></i>
                    </li>
                    <li>
                      <i class="fas fa-star fa-xs"></i>
                    </li>
                    <li>
                      <i class="fas fa-star fa-xs"></i>
                    </li>
                    <li>
                      <i class="fas fa-star fa-xs"></i>
                    </li>
                  </ul>
                </div>
                <div>
                  <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-dark btn-rounded btn-sm"
                    data-mdb-ripple-color="dark">+ Follow</button>
                  <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-dark btn-rounded btn-sm"
                    data-mdb-ripple-color="dark">See profile</button>
                  <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-dark btn-floating btn-sm"
                    data-mdb-ripple-color="dark"><i class="fas fa-comment"></i></button>
                </div>
              </div>

<%= render @profile %>

<div>
  <%= link_to "Edit this profile", edit_profile_path(@profile) %> |
  <%= link_to "Back to profiles", profiles_path %>

  <%= button_to "Destroy this profile", @profile, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>